version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_tarefas
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tarefasdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
