# fly.toml - configuração para back-tarefas
app = "back-tarefas-ancient-voice-361"
primary_region = "gru"

[build]
  # Use build args se precisar
  # build_args = { FORCE_REBUILD = "true" }

[deploy]
  # Prisma: apenas se você tiver migrations
  release_command = "npx prisma migrate deploy"

[env]
  # Variáveis de ambiente
  DATABASE_URL = "<COLOQUE_AQUI_SEU_DATABASE_URL>"

[http_service]
  internal_port = 3000      # mesma porta que o Nest está ouvindo
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
